# Using version 2.6 of the compose format
version: '3.6'

# Services Section
services:
  # nginxproxy:
  #   image: jwilder/nginx-proxy:latest
  #   environment:
  #     - VIRTUAL_HOST=$DOMAIN
  #     - DEFAULT_HOST=$DOMAIN
  #     # VIRTUAL_HOST: 20x.sakai.dev
  #   networks:
  #     - proxy
  #     # proxy:
  #     #   aliases:
  #     #     - 20x.sakai.dev
  #   volumes:
  #     - "/var/run/docker.sock:/tmp/docker.sock"
  #   ports:
  #     - "80:80"
  #   deploy:
  #     mode: global
  #
  # HAProxy to handle everything.
  # 
  # stackproxy:
  #   image: dockercloud/haproxy:1.6.7
  #   environment:
  #     - "TIMEOUT=connect 5400000, client 5400000, server 5400000"
  #     - "SKIP_FORWARDED_PROTO=true"
  #     - "VIRTUAL_HOST=$DOMAIN"
      # TIMEOUT: "connect 5300000, client 5400000, server 5400000"
      # SKIP_FORWARDED_PROTO: "true"
      # VIRTUAL_HOST: 20x.sakai.dev
    # networks:
    #   - proxy
      # proxy:
      #   aliases:
      #     - 20x.sakai.dev
    # volumes:
    #   - "/var/run/docker.sock:/var/run/docker.sock"
      # - "haproxy_config:/usr/local/etc/haproxy"

    # ports:
    #   - "80:80"
    # deploy:
    #   mode: global
  
  # Node builder for rapid theme development
  
  # node:
  #   image: node
  #   volumes:
  #     - sakai_source:/home/node/app/source/sakai/library
  #     - sakai_deploy:/deploy
  #     - "$PWD/lib/node_entry.sh:/node_entry.sh"
  #     - "$PWD/CONFIG/maven/zshrc:/root/.zshrc"
  #   entrypoint: bash /node_entry.sh
  #   environment:
  #     - "SERVICE_PORTS=3333"
  #     - "VIRTUAL_PORT=3333"
  #     # - "VIRTUAL_HOST_WEIGHT=5"
  #     - VIRTUAL_HOST=sakai-node.localhost
  #   deploy:
  #     replicas: 1
  #   user: "node"
  #   working_dir: /home/node/app
  #   networks:
  #     - proxy

  # 
  # Shell In A Box on a maven container.
  #
  builder:
    # image: maven:3.6.3-jdk-8
    # image: markhobson/maven-chrome:jdk-8
    image: atlassianlabs/docker-node-jdk-chrome-firefox
    # image: gitlab-registry.oit.duke.edu/mg287/docker/maven-node-chrome-ff:latest
    # context: .
    # dockerfile: builder.Dockerfile
    # user: 1000
    volumes:
      - "$PWD/lib/maven_entry.sh:/maven_entry.sh"
      - "$PWD/CONFIG/maven/zshrc:/root/.zshrc"
      - "$PWD/CONFIG/maven/settings.xml:/usr/share/maven/conf/settings.xml"
      - "$PWD/CONFIG/maven/black_on_white.css:/black_on_white.css"
      - sakai_source:/source
      - sakai_deploy:/deploy
      - maven_cache:/root/.m2
      - npm_cache:/root/.npm
      # - "/var/run/dbus/system_bus_socket:/var/run/dbus/system_bus_socket"
    entrypoint: bash /maven_entry.sh
    environment:
      - "SERVICE_PORTS=4200"
      - "VIRTUAL_PORT=4200"
      # - "VIRTUAL_HOST_WEIGHT=5"
      - VIRTUAL_HOST=sakai-console.localhost
      - "MAVEN_OPTS=-Xmx8000m"
    networks:
      - proxy

  # 
  # MySQL service.
  #
  mysql:
    # Docker official image for MySQL 5.5
    image: mysql:5.7.26
    # Extra startup parameters for MySQL
    command: --character-set-server=utf8 --collation-server=utf8_general_ci --ssl=0
    # Environment Variables
    environment:
      MYSQL_ROOT_PASSWORD: toor
      MYSQL_DATABASE: sakai
      MYSQL_USER: sakai
      MYSQL_PASSWORD: examplepassword
    # Networks from section near bottom 
    networks:
      - mysql
    volumes:
      - mysql_data:/var/lib/mysql

  # 
  # Sakai Service
  #
  sakai:
    image: tomcat:9.0.46-jdk8
    environment:
      - "CATALINA_OPTS_MEMORY=-Xms2000m -Xmx8000m"
      - "CATALINA_OPTS=-server -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled -XX:+UseCompressedOops -XX:+UseCMSInitiatingOccupancyOnly -XX:CMSInitiatingOccupancyFraction=80 -XX:TargetSurvivorRatio=90 -Djava.awt.headless=true -Dsun.net.inetaddr.ttl=0 -Dsakai.component.shutdownonerror=true -Duser.language=en -Duser.country=US -Dsakai.home=/usr/local/sakai/properties -Dsakai.security=/usr/local/tomcat/sakai -Duser.timezone=US/Eastern -Dsun.net.client.defaultConnectTimeout=300000 -Dsun.net.client.defaultReadTimeout=1800000 -Dorg.apache.jasper.compiler.Parser.STRICT_QUOTE_ESCAPING=false -Dsun.lang.ClassLoader.allowArraySyntax=true -Dhttp.agent=Sakai -Djava.util.Arrays.useLegacyMergeSort=true"
      - "JAVA_OPTS=-Dspring.config.location=/usr/local/sakai/properties/sakai.properties -Dsakai.demo=true"
      - "SERVICE_PORTS=8080"
      - VIRTUAL_PORT=8080
      - VIRTUAL_HOST=sakai.localhost
      - "HTTP_CHECK=GET / \"HTTP/1.1\\r\\nHost: ingress.proxy\""
    networks:
      mysql:
      mail:
      proxy:
    volumes:
      - "$PWD/lib/mysql-connector-java-5.1.47.jar:/usr/local/tomcat/lib/mysql-connector-java-5.1.47.jar"
      - "$PWD/lib/tomcat_entry_nogl_nosearch.sh:/tomcat_entry.sh"
      - "$PWD/CONFIG/tomcat/server.xml:/usr/local/tomcat/conf/server.xml"
      - "$PWD/CONFIG/tomcat/context.xml:/usr/local/tomcat/conf/context.xml"
      - "$PWD/CONFIG/tomcat/web.xml:/usr/local/tomcat/conf/web.xml"
      - "$PWD/CONFIG/sakai/sakai.properties:/usr/local/sakai/es.properties"
      - "sakai_deploy_components:/usr/local/tomcat/components"
      - "sakai_deploy_lib:/usr/local/tomcat/sakai-lib"
      - "sakai_deploy_webapps:/usr/local/tomcat/webapps"
      - "sakai_root:/usr/local/tomcat/webapps/ROOT"
      - "$PWD/DATA/ROOT/index_dev_tools.html:/usr/local/tomcat/webapps/ROOT/index.html"
    entrypoint: bash /tomcat_entry.sh

  # 
  # Mailcatcher service      
  #
  mailcatcher:
    # 3rd party repo fro Mailcatcher (Fake mail server for development and testing)
    image: tophfr/mailcatcher:0.7.1
    environment:
      - "VIRTUAL_HOST_WEIGHT=5"
      - "VIRTUAL_HOST=sakai-mail.localhost"
      - "SERVICE_PORTS=1080"
      - "VIRTUAL_PORT=1080"
    command: "mailcatcher --no-quit --foreground --ip=0.0.0.0 --http-path=/mail"
    # Networks from section near bottom
    networks:
      - mail
      - proxy

  #
  # PHPMyAdmin Service
  #
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:4.7
    environment:
      - "PMA_ARBITRARY=1"
      - "PMA_ABSOLUTE_URI=http://127.0.0.1/pma"
      - "VIRTUAL_HOST_WEIGHT=5"
      - "VIRTUAL_HOST=sakai-pma.localhost"
      - "SERVICE_PORTS=80"
      - "VIRTUAL_PORT=80"
      - "EXTRA_SETTINGS=reqrep ^([^\\ :]*)\\ /pma/(.*) \\1\\ /\\2"
    networks:
      - mysql
      - proxy
    
networks:
  mysql:
    driver: overlay
  mail:
    driver: overlay
  proxy:
    # driver: overlay
    external: true

volumes:
  sakai_source:
    driver_opts:
      type: none
      device: $PWD/sakai/source
      o: bind
  sakai_root:
    driver_opts:
      type: none
      device: $PWD/DATA/ROOT
      o: bind
  sakai_deploy:
    driver_opts:
      type: none
      device: $PWD/sakai/deploy
      o: bind
  sakai_deploy_components:
    driver_opts:
      type: none
      device: $PWD/sakai/deploy/components
      o: bind
  sakai_deploy_lib:
    driver_opts:
      type: none
      device: $PWD/sakai/deploy/lib
      o: bind
  sakai_deploy_webapps:
    driver_opts:
      type: none
      device: $PWD/sakai/deploy/webapps
      o: bind
  maven_cache:
    driver_opts:
      type: none
      device: $PWD/DATA/maven
      o: bind
  npm_cache:
    driver_opts:
      type: none
      device: $PWD/DATA/npm
      o: bind
  mysql_data:
    driver_opts:
      type: none
      device: $PWD/DATA/mysql
      o: bind
  sakai_config:
    driver_opts:
      type: none
      device: $PWD/CONFIG/sakai
      o: bind
  haproxy_config:
    driver_opts:
      type: none
      device: $PWD/CONFIG/haproxy
      o: bind
